# Unix submit description file
# sleep.sub -- simple sleep job
universe		= vanilla
getenv			= True
executable              = busy.sh
log                     = Busy.log
output                  = Busy.$(Process).out
error                   = Busy.$(Process).error
#request_cpus = 5
#request_GPUs = 1
#request_memory = 5GB
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

arguments		= 1500
queue 450

